"""init

Revision ID: fb4ae4c5444f
Revises: 
Create Date: 2025-12-02 20:56:43.560033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb4ae4c5444f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_article',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_article'))
    )
    op.create_table('sentences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sentences'))
    )
    op.create_index(op.f('ix_sentences_text'), 'sentences', ['text'], unique=True)
    op.create_table('words',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_words'))
    )
    op.create_index(op.f('ix_words_text'), 'words', ['text'], unique=True)
    op.create_table('word_lookups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sentence_id', sa.UUID(), nullable=True),
    sa.Column('word_id', sa.UUID(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], name=op.f('fk_word_lookups_sentence_id_sentences')),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], name=op.f('fk_word_lookups_word_id_words')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_word_lookups'))
    )
    op.create_index(op.f('ix_word_lookups_sentence_id'), 'word_lookups', ['sentence_id'], unique=False)
    op.create_index(op.f('ix_word_lookups_word_id'), 'word_lookups', ['word_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_word_lookups_word_id'), table_name='word_lookups')
    op.drop_index(op.f('ix_word_lookups_sentence_id'), table_name='word_lookups')
    op.drop_table('word_lookups')
    op.drop_index(op.f('ix_words_text'), table_name='words')
    op.drop_table('words')
    op.drop_index(op.f('ix_sentences_text'), table_name='sentences')
    op.drop_table('sentences')
    op.drop_table('raw_article')
    # ### end Alembic commands ###
